### ISSUE TITLE
Nyan cat web site is gone

### ISSUE THREAD

**Issue by amitp** [TeMPOraL/nyan-mode#18]
The home page URL in melpa and also on the github version is http://nyan-mode.buildsomethingamazing.com but that site is no longer showing nyan-mode. Is there an updated home page url?

**Comment by TeMPOraL** [comment]
No, I have transient domain issues. Should be resolved in a week.

**Comment by amitp** [comment]
Aha, ok, thank you!

**Comment by quazgar** [comment]
Not resolved (anymore?) at the moment.
