### ISSUE TITLE
Invalid image type 'xpm'

### ISSUE THREAD

**Issue by computersarecool** [TeMPOraL/nyan-mode#21]
This is the error I get when I try to enact nyan mode. I see the note about the .png branch - can you please tell me how I can install it?

**Comment by andyque** [comment]
I also meet this issue, I'm using GNU Emacs 24.4 on MacOS X 10.10.1.

**Comment by hotpxl** [comment]
+1, same issue with GNU Emacs 24.5.1 on MacOS X 10.10.3

**Comment by mbme** [comment]
issue resolved for me by installing `emacs-app` package from macports

**Comment by hotpxl** [comment]
Thanks for sharing.

**Comment by mbme** [comment]
everyone deserves nyan cat in their modeline! :)

**Comment by enko** [comment]
This error also happens if you have an emacs version with no X support, for example emacs-nox on debian, which I use on my server to read mail. Would be awesome if nyan-mode would work work there too.
