### ISSUE TITLE
Handle especially small windows

### ISSUE THREAD

**Issue by aengelberg** [TeMPOraL/nyan-mode#23]
If I have especially small windows in my frame (e.g. a sixteenth of the maximized frame) nyan cat will push all of the extra information out of the lower bar (modes, line number, git info, etc.). Perhaps it would be best to disable nyan cat for those cases, or make a resizable nyan that adapts to the window size?

**Comment by TeMPOraL** [comment]
Good point, I'll look into it.

**Comment by TeMPOraL** [comment]
Done! The value defaults to 64 Emacs units (whatever it is (window-width) returns) and is customizable!
