### ISSUE TITLE
Description URL is expired

### ISSUE THREAD

**Issue by wasamasa** [TeMPOraL/nyan-mode#25]
More specifically, http://nyan-mode.buildsomethingamazing.com/.  Perhaps it would make more sense to use Github's page service?

**Comment by TeMPOraL** [comment]
I updated it in 5c3c7c1f217423ea9e0e8ad2df4f999ac71a4232, before tagging a release, so it shouldn't be showing up anywhere. Where did you find it?

**Comment by wasamasa** [comment]
> I updated it in 5c3c7c1, before tagging a release, so it shouldn't be
showing up anywhere. Where did you find it?

It shows up in Github's description of the repository, right under its
name.

**Comment by TeMPOraL** [comment]
Oh.

Call it banner blindness :).
Thanks!
