### ISSUE TITLE
wish: clicking the nyan-bar to scroll the file

### ISSUE THREAD

**Issue by ArneBab** [TeMPOraL/nyan-mode#3]
It would be pretty cool to be able to click the nyan-bar to scroll to that position in the file. 

Or to drag nyan to where I want to read. 

The next step would then be

(scroll-bar-mode -1) ; nyan wins :)

**Comment by TeMPOraL** [comment]
Clicking is now supported; a test deployment is in dev branch. :).

**Comment by TeMPOraL** [comment]
Done - see new release - v1.1.0.
