### ISSUE TITLE
if: Symbol’s value as variable is void: colors-enable-nyan-cat-progress-bar

### ISSUE THREAD

**Issue by casouri** [TeMPOraL/nyan-mode#36]
Emacs complain about this but when I went into config.el in colors layer, ```colors-enable-nyan-cat-progress-bar``` is there

```
(defvar colors-enable-nyan-cat-progress-bar nil
  "If non nil all nyan cat packages are enabled (for now only `nyan-mode').")
```

I use spacemacs and add nan-mode into it.
Any ideas?

**Comment by TeMPOraL** [comment]
What do you mean "complain about this"? Could you paste here the exact complaint Emacs makes?
