### ISSUE TITLE
Nyan only in text mode on Emacs 26.2

### ISSUE THREAD

**Issue by novoid** [TeMPOraL/nyan-mode#43]
After updating my Emacs from 25.x to 26.2, my Nyan cat is in text only, not displaying the xpm graphics.

nyan-mode-1.1.2 from elpa with emacs-version 26.2 from https://github.com/m-parashar/emax64/releases/tag/emax64-26.2-20190417 on latest Windows 10.

I checked the `img` folder and made sure that my Emacs is able to display the xpm files as graphic which it does.

So maybe there is an issue with the latest Emacs version. Let me know if I should check something.

I noticed, that _all_ of my mode-line icons are replaced with their text counterparts: https://github.com/m-parashar/emax64/issues/23 - maybe it is good to keep this issue open for others who recognize this behavior. I'll close it when the other issue is solved.

**Comment by cheeesy** [comment]
I am not that experienced with Emacs graphics, but under Emacs 26.3 I see no images as well.

**Comment by cheeesy** [comment]
Update: I just realized I had been running emacs -nw the whole time. With Graphical Emacs it works.

**Comment by TeMPOraL** [comment]
Looking at the issue you linked, is the problem ultimately the lack of support of XPM images on Windows? If so, I'll need to investigate whether Emacs can display PNGs in mode line, and add a platform feature check to choose between the two.

**Comment by novoid** [comment]
I don't run the Windows machine any more. AFAIR I did set up the XPM support. However, I can't test it any more.

I'll close this issue since there is no other person subscribed to this issue.

Sorry for your effort these days.
